#!/usr/bin/env bash
set -e

if [ $# -ne 1 ]; then
    echo "Usage: $0 NAME"
    exit 1
fi

NAME="$1"

mkdir "$NAME"
cd "$NAME"
mkdir src
touch src/lib.rs

cat > README.md <<EOF
# **$NAME**

 
[![Sponsors](https://img.shields.io/github/sponsors/QuackHack-McBlindy?logo=githubsponsors&label=Sponsor&style=flat&labelColor=ff1493&logoColor=fff&color=rgba(234,74,170,0.5) "")](https://github.com/sponsors/QuackHack-McBlindy) [![Buy Me a Coffee](https://img.shields.io/badge/Buy%20Me%20a%20Coffee-Sponsor?style=flat&logo=buymeacoffee&logoColor=fff&labelColor=ff1493&color=ff1493)](https://buymeacoffee.com/quackhackmcblindy)


\`$NAME\` is a crate designed for bare metal and \`no_std\` projects. 


## **Installation**

  
Add **$NAME** as a dependency in \`Cargo.toml\`.

\`\`\`toml
[dependencies]
$NAME = "0.1.0"
\`\`\`
  


<br>

## **Example usage**





<br>

## **Lisence**

**MIT**  
<br>
Contributions are welcomed.


<br><br>

## **☕**

[![Sponsors](https://img.shields.io/github/sponsors/QuackHack-McBlindy?logo=githubsponsors&label=Sponsor&style=flat&labelColor=ff1493&logoColor=fff&color=rgba(234,74,170,0.5) "")](https://github.com/sponsors/QuackHack-McBlindy) [![Buy Me a Coffee](https://img.shields.io/badge/Buy%20Me%20a%20Coffee-Sponsor?style=flat&logo=buymeacoffee&logoColor=fff&labelColor=ff1493&color=ff1493)](https://buymeacoffee.com/quackhackmcblindy)
> Like my work?   
> Buy me a coffee, or become a sponsor.  
> Thanks for supporting open source!    

♥️₿ *Wallet:* ``pungkula.x\`   
<a href="https://www.buymeacoffee.com/quackhackmcblindy" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 60px !important;width: 217px !important;" ></a>

EOF

mkdir scripts
cat > scripts/release.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

CRATE_NAME=$(grep '^name =' Cargo.toml | head -1 | sed 's/name = "\(.*\)"/\1/')
echo "Releasing crate: $CRATE_NAME"


if ! command -v cargo &> /dev/null; then
    echo "🚫 cargo not found"
    echo "Forgot nix develop?"    
    exit 1
fi

if ! git diff --quiet; then
    echo "🚫 Working directory is not clean. Commit or stash changes first."
    exit 1
fi



current_version=$(grep '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
echo "Current version: $current_version"

IFS='.' read -r major minor patch <<< "$current_version"
new_patch=$((patch + 1))
new_version="$major.$minor.$new_patch"
echo "New version: $new_version"


cp Cargo.toml Cargo.toml.bak
cp README.md README.md.bak


if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/^version = \".*\"/version = \"$new_version\"/" Cargo.toml
else
    sed -i "s/^version = \".*\"/version = \"$new_version\"/" Cargo.toml
fi


if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/$CRATE_NAME = \".*\"/$CRATE_NAME = \"$new_version\"/" README.md
else
    sed -i "s/$CRATE_NAME = \".*\"/$CRATE_NAME = \"$new_version\"/" README.md
fi

echo "Updated version to $new_version"


git add Cargo.toml README.md
git commit -m "chore: bump version to $new_version"
git tag "v$new_version"

cargo clean
if cargo publish; then
    echo "pblished successfully"
    git push origin main --tags
    echo "🚀 Released version $new_version"
else
    echo "❌ cargo publish failed. Rolling back..."

    mv Cargo.toml.bak Cargo.toml
    mv README.md.bak README.md


    git reset --hard HEAD~1
    git tag -d "v$new_version"

    echo "Rollback complete. Version unchanged."
    exit 1
fi

rm -f Cargo.toml.bak README.md.bak
EOF

chmod +x scripts/release.sh

cat > Cargo.toml <<EOF
[package]
name = "$NAME"
version = "0.1.0"
authors = ["QuackHack-McBlindy"]
license = "MIT"
description = "bare metal no_std components"
repository = "https://github.com/QuackHack-McBlindy/$NAME"
readme = "README.md"
keywords = ["esp-hal", "embedded", "esp32"]
categories = ["embedded"]
edition = "2024"

[dependencies]

EOF

cat > .gitignore <<EOF
**/dump
**/*.env
dump
.env
# will have compiled files and executables
debug/
target/

# Editor configuration
.vscode/
.zed/
.helix/
.nvim.lua

# These are backup files generated by rustfmt
**/*.rs.bk

# MSVC Windows builds of rustc generate these, which store debugging information
*.pdb

# RustRover
#  JetBrains specific template is maintained in a separate JetBrains.gitignore that can
#  be found at https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore
#  and can be added to the global gitignore or merged into this file.  For a more nuclear
#  option (not recommended) you can uncomment the following to ignore the entire idea folder.
#.idea/


# Ignore .DS_Store file in mac
**/.DS_Store
EOF

cat > LICENSE <<EOF
MIT License

Copyright (c) 2024 pungkula

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF


cat > .envrc <<EOF
git checkout main
EOF
